name: 'action-monorepo-version-tags-lifecycle'
description: 'Generate version tags on a monorepo with multiple components'
branding:
  icon: 'tag'
  color: 'gray-dark'

inputs:
  mode:
    description: 'Execution mode can be "product" "component"'
    required: true
  type:
    description: 'Execution type can be "pre-release" "release" "fix" "final" "new-release-branch"'
    required: true
  current-tag:
    description: 'Current tag of a component, e.g. "component-v0.4.0".'
    required: false
    default: 'v0.0.0'
  current-major:
    description: 'Current major version of the product.'
    required: false
    default: '0'
  component-prefix:
    description: 'Component prefix, e.g. "component1-".'
    required: false
  release-branch-prefix:
    description: 'Release branch prefix, e.g. "release/v".'
    required: false
  pre-release-name:
    description: 'A pre release name, e.g. "alpha" or "rc"'
    required: false
  tag-branch:
    description: 'Branch to create a version tag, e.g. "main"'
    required: false
    default: 'main'
  update-versions-in:
    description: 'String representation of an array of objects with file/property keys. If provided the action will update those files/properties with the version that is being released.'
    required: false
    default: false
  strip-component-from-tag:
    description: 'If component prefix should be removed from the tag when returning it or using it in a version file'
    required: false
    default: false
  commit-message:
    description: 'The message in the commit for version updates.'
    required: false
    default: 'Update version file [skip-ci]'
  commit-author:
    description: 'The author for the commit in the version updates.'
    required: false
    default: 'Tagger Action'
  commit-author-email:
    description: 'The author email for the commit in the version updates.'
    required: false
    default: 'no-reply-tagger-action@igz.es'
  dry-run:
    description: 'Enable dry run mode, e.g. "true" or "false"'
    required: false
    default: 'false'

outputs:
  tag:
    description: 'The new version tag that was created'

runs:
  using: 'node12'
  main: 'dist/index.js'
