name: Build Action

on:
  pull_request:
    branches:
      - main
    paths:
      - "src/**/*"
  push:
    branches:
      - main
    paths:
      - "src/**/*"

env:
  GITHUB_TOKEN: ${{ secrets.PATNAME }}

jobs:
  quality-checks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test

  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-20.04
    needs: quality-checks
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
      - name: Commit files
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          if [[ `git status --porcelain` ]]; then
              git commit -m "Update build [skip-ci]" -a
              git push
          fi
